version: "3.7"
services:
  app:
    build:
      args:
        user: user123
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: some-service
    container_name: some-service-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - some-service

  db:
    image: postgres:14.1
    container_name: some-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - some-service

  nginx:
    image: nginx:alpine
    container_name: some-service-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - some-service

networks:
    some-service:
        driver: bridge
